spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config  #1
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"